### ISSUE TITLE
Add link to bookmark in bookmark detailed view

### ISSUE THREAD

**Issue by TomCasavant** [ckolderup/postmarks#147]
Similar to how you have the @username@domain on the about page, it might be useful to add in a path to the bookmark that someone can look up in order to comment
it looks like they're stored in the format: "https://{{domain}}/m/{{activity_id}}" but doing a search for that url doesn't seem to bring up the post so I'm not certain what would be needed for that

**Comment by ckolderup** [comment]
Hmm, yeah. I *would* expect that pasting the "/m/a-{guid}" format would work right now, so we'll have to see what we're returning there vs what Mastodon is expecting. But also we don't really expose those URLs right now, and we should make sure that the "/bookmark/{incremental id}" canonical URL redirects properly as well so that once we've fixed both halves, it comes up correctly in Mastodon.

Thanks for reporting!

**Comment by TomCasavant** [comment]
> it looks like they're stored in the format: "https://{{domain}}/m/{{activity_id}}" but doing a search for that url doesn't seem to bring up the post so I'm not certain what would be needed for that

Hm, I still can't search for a post in that format from mastodon.social. But I have a takahe server setup and it has no issue searching for posts setup like that
